# Generated by Django 3.1.4 on 2020-12-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TDM_NHANVIEN',
            fields=[
                ('MANV', models.CharField(max_length=200)),
                ('TENNV', models.CharField(max_length=200)),
            ],
        ),
    ]
